---
- name: "Setup User and Home Directory"
  gather_facts: no
  hosts: hostname
  vars_files:
    - ../usr_create_var.yml
  tasks:
    - name: "Create User"
      user:
        name: "{{username}}"
        shell: /bin/bash
        create_home: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa